apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace: fred
  labels:
    app: test-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30000
  selector:
    app: test-app

